version: '3.3'

services:
    nginx_api-example-laravel:
        container_name: nginx_api-example-laravel
        build:
            context: nginx
        volumes:
            - ${APP_PATH}:/app
        depends_on:
            - php_api-example-laravel
        ports:
            - 80:80
        networks:
            api-example-laravel:
                ipv4_address: 10.5.0.2

    php_api-example-laravel:
        container_name: php_api-example-laravel
        build:
            context: php8-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        networks:
            api-example-laravel:
                ipv4_address: 10.5.0.3
        volumes:
            - ${APP_PATH}:/app
        links:
            - pgsql_api-example-laravel
        environment:
            XDEBUG_CONFIG: remote_host=${IP_ADDRESS}

    pgsql_api-example-laravel:
        container_name: pgsql_api-example-laravel
        image: postgres:12
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - 5432:5432
        networks:
            api-example-laravel:
                ipv4_address: 10.5.0.4

    adminer_api-example-laravel:
        container_name: adminer_api-example-laravel
        image: adminer
        ports:
            - 8080:8080
        networks:
            api-example-laravel:
                ipv4_address: 10.5.0.5

    mailcatcher_api-example-laravel:
        container_name: mailcatcher_api-example-laravel
        image: schickling/mailcatcher
        ports:
            - 1080:1080
        networks:
            api-example-laravel:
                ipv4_address: 10.5.0.6

networks:
    api-example-laravel:
        driver: bridge
        ipam:
            config:
            - subnet: 10.5.0.0/16

volumes:
    pgsql_api-example-laravel_data_container:
